// // use concatenation to sum up 5+1 with their variables name*/
// const num1=5;
// const num2=10;
// const output= (num1 + num2);
// console.log(output);
// // display "hello world" on your browser
// document.write("hello world");




// /*use concatenation to join two string with their variable name*/
// const firstName="Akorede";
// const lastName="IBRAHIM"
// const hisName=(firstName +" "+lastName);
// console.log(hisName);


// string data type

// let str1 = "ALABIAN SOLUTION"

// console.log(str1);

// let  quote = '"this is alabian solution school"'
// console.log(typeof quote);
// console.log(quote);

// let apro =  "my father\'s name";
// console.log(typeof apro);
// console.log(apro);


// string data type

// let str1 = "HELLO WORLD"
// console.log(typeof str1);
// console.log(str1);



// Number data type
// let num1 =50;
// console.log(typeof num1);
// console.log(num1);

// let num3 = 2.15;
// console.log(num3);
// let num2 =7e5
// console.log(typeof num2);
// console.log(num2);


// // Not a Number
// let nan = NaN;
// console.log(nan);

// // boolean data type

// let isTrue = true;
// console.log(typeof isTrue);
// console.log(isTrue);

// let isTrue = false;
// console.log(typeof isTrue);
// console.log(isTrue);

// undefined data type

// let firstName;
// console.log(firstName);


// null data type

// let noThing = null;
// console.log(noThing);
 

// concatenation

// let str3 = "kore teach the class";
// let str4 = "and gift is laughing";
// const output  =(str3 + " " +str4)
// console.log(output);


// concatenation
// let num4 = 5;
// let num6 = 15;

// template literal
// const calculate = `${num4} + ${num6} = ${num4 + num6}`
// console.log(calculate);

let name = "Mark"
let company = "Alabian Solution";

const result1 = `${name} work at ${company}`

console.log(result1);


// operation of numbers

// sum

let x = 20;
let y = 30;

let sum = x + y;
console.log(sum);

// minus

let a = 20;
let b = 15;

let minus = a - b;
console.log(minus);

// multiplication

let c = 20;
let d = 10;
let multiply = c * d;
console.log(multiply);

// division

let e = 20;
let f = 10;

let divide = e / f;
console.log(divide);

// modulus

let g = 20;
let h = 9;

let mod = g % h;
console.log(mod);

// increment

let i = 20
i++;

let o = i;
console.log(o);

// decrement
let j = 20;
j--;
console.log(j);

// **

let k = 2;
let l = k ** 5;

console.log(l);


let m = 5;
m -=5;

console.log(m);

// comparison operation

let n = 5;

// loosely equal to
console.log(n == "5");
console.log(n == 5);
console.log(n == "8");
console.log(n == 8);

// loosely not equal to
console.log(n != "5");
console.log(n != 5);
console.log(n != "8");
console.log(n != 5);

let product = "bag";

console.log(product == " shoes");
console.log( product != "shoes");
