// use concatenation to sum up 5+1 with their variables name*/
const num1=5;
const num2=10;
const output= (num1 + num2);
console.log(output);
// display "hello world" on your browser
document.write("hello world");




/*use concatenation to join two string with their variable name*/
const firstName="Akorede";
const lastName="IBRAHIM"
const herName=(firstName +" "+lastName);
console.log(herName);


